const f2f_b6_stories = [
	{
		track:"01.01",
		en:"AMY So, Ann, why did you suggest this book? <br>\
ANN Well, I've bought quite a few self-help books over the past few months and 1 suggested this one for the book club because my brother's been telling me to read it for ages. Apparently, it's sold over 16 million copies and it's still selling well, which surprised me because it's pretty basic stuff, really. I mean, you know, smile at people that's a bit obvious, isn't it? Or, make the other person feel important. That's pretty obvious, too. But as my brother said, if what Carnegie's saying is that self-evident, then why don't people do it? And he's got a point.<br>\
SY Yeah, I agree with your brother there. And OK, even if some of the points he makes in the book seem basic, I mean, I still find it fascinating. Actually, I think people are getting fed up with me talking about it! I've told at least ten people about it at work this week. To be honest, it's the first time I've read a book like this, and even though I haven't quite finished it yet - I mean, I've, I've read about 150 pages so far - I totally agree with what he's saying. I mean, the bit where it says 'as a rule we aren't good listeners,' I mean, that's so true. I mean we're usually just waiting to speak. If someone's talking about something that's happening to them, or happened to them, then most people are just waiting to butt in, aren't they, with, you know, 'Same thing happened to me,' and off they go, you know, wittering on about themselves. I mean, I think Carnegie's right when he says that if you want people to like you, you've got to learn to really pay attention to what they're saying. Yeah, I mean, actually encourage the other person to talk about themselves, by asking questions, I mean, showing that you're interested in them. Anyway, I've been trying to be a more attentive listener and not interrupt, but it, I tell you, it takes some self-discipline, I can... Soon as you've finished reading it, I mean, I'm going to give it to my brother, because he's got no social skills whatsoever! I mean, it's true! What about you, Dean. Did you like it?<br>\
DEAN Yeah, I did, and to be honest, I wasn't expecting to. Like Sy, I agree with a lot of what it says, like the bit about how important it is to remember people's names. Never thought about that before, but a friend of mine, John, he's brilliant at that. And it works, especially when he's chatting up girls. For instance, last night we went for a pizza. I went to the loo. I hadn't been gone for more than a minute, but by the time I got back to the table, he'd introduced himself to the three girls at the table next to ours and learnt their names. There he was, saying stuff like 'So, Clare, how are you enjoying London?' You could see Clare was thinking 'What a nice guy.' And I'm sure it was just because he'd called her by her first name. Actually, since Ann suggested this one I've read a couple of his other books. <br>\
ANN Yeah, I bought one of his other books recently, too.<br>\
AMY Well, during the last couple of weeks I've actually been trying out some of Carnegie's suggestions, as well, you know, like the one where he goes on about how powerful a smile is.<br>\
ANN Yeah, but that's true, though, isn't it? I mean, most people walk around with a scowl on their face. So, that when someone actually does smile at you, it really makes an impression.<br>\
AMY It does! You know he suggested smiling at everyone you come into contact with for a week and note what happens. Well, I did and it really does make a difference. Like, I've been going to the same train station for years and up until now, I've never really had any contact with the guy in the ticket office other than, 'Return to Richmond, please.' So, I started with him. You know, a smile and a bit of eye contact and it was amazing! He's been really chatty ever since. Much nicer way to start the day. And remember the bit where Carnegie says, even if you don't feel like smiling, force yourself to, 'cos smiling actually brings on a nice feeling. Well, I've been trying to do that too, and it works!<br>\
ANN Yeah, it's a different mindset, isn't it? And I loved that quote that, the Chinese proverb, 'A man without a smiling face must not open a shop!' I know, I know a few shop assistants who could learn from that, especially..."
		,vi:"AMY Vậy Ann, tại sao bạn lại gợi ý cuốn sách này? <br>\
ANN À, tôi đã mua khá nhiều sách tự lực trong vài tháng qua và tôi đã gợi ý cuốn này cho câu lạc bộ sách vì anh trai tôi đã bảo tôi đọc nó từ lâu rồi. Rõ ràng là nó đã bán được hơn 16 triệu bản và vẫn đang bán chạy, điều đó khiến tôi ngạc nhiên vì thực sự nó là những thứ khá cơ bản. Ý tôi là, bạn biết đấy, mỉm cười với mọi người thì hơi hiển nhiên, phải không? Hoặc, khiến người khác cảm thấy mình quan trọng. Điều đó cũng khá hiển nhiên. Nhưng như anh trai tôi đã nói, nếu những gì Carnegie nói là hiển nhiên như vậy, thì tại sao mọi người lại không làm vậy? Và anh ấy có lý.<br>\
SY Vâng, tôi đồng ý với anh trai bạn ở điểm đó. Và được rồi, ngay cả khi một số điểm anh ấy đưa ra trong cuốn sách có vẻ cơ bản, ý tôi là, tôi vẫn thấy nó hấp dẫn. Thực ra, tôi nghĩ mọi người đang phát ngán khi tôi nói về nó! Tôi đã nói với ít nhất mười người về nó ở nơi làm việc trong tuần này. Thành thật mà nói, đây là lần đầu tiên tôi đọc một cuốn sách như thế này, và mặc dù tôi vẫn chưa đọc hết - ý tôi là, tôi đã đọc khoảng 150 trang cho đến nay - tôi hoàn toàn đồng ý với những gì ông ấy nói. Ý tôi là, đoạn nói rằng 'theo nguyên tắc, chúng ta không phải là người biết lắng nghe', ý tôi là, điều đó quá đúng. Ý tôi là chúng ta thường chỉ chờ để nói. Nếu ai đó nói về điều gì đó đang xảy ra với họ, hoặc đã xảy ra với họ, thì hầu hết mọi người chỉ chờ để xen vào, phải không, với, bạn biết đấy, 'Điều tương tự đã xảy ra với tôi', và họ nói, bạn biết đấy, nói huyên thuyên về bản thân họ. Ý tôi là, tôi nghĩ Carnegie đã đúng khi ông ấy nói rằng nếu bạn muốn mọi người thích bạn, bạn phải học cách thực sự chú ý đến những gì họ đang nói. Vâng, ý tôi là, thực sự khuyến khích người khác nói về bản thân họ, bằng cách đặt câu hỏi, ý tôi là, cho thấy rằng bạn quan tâm đến họ. Dù sao thì, tôi đã cố gắng trở thành một người lắng nghe chú ý hơn và không ngắt lời, nhưng, tôi nói cho bạn biết, cần phải có một chút kỷ luật, tôi có thể... Ngay khi bạn đọc xong, ý tôi là, tôi sẽ đưa nó cho anh trai tôi, vì anh ấy không có bất kỳ kỹ năng xã hội nào! Ý tôi là, điều đó đúng! Còn anh thì sao, Dean. Anh có thích nó không?<br>\
DEAN Vâng, tôi thích, và thành thật mà nói, tôi không mong đợi điều đó. Giống như Sy, tôi đồng ý với nhiều nội dung trong đó, như đoạn nói về tầm quan trọng của việc nhớ tên mọi người. Tôi chưa bao giờ nghĩ về điều đó trước đây, nhưng một người bạn của tôi, John, anh ấy rất giỏi việc đó. Và nó hiệu quả, đặc biệt là khi anh ấy tán tỉnh các cô gái. Ví dụ, tối qua chúng tôi đã đi ăn pizza. Tôi đã đi vệ sinh. Tôi đã không đi quá một phút, nhưng khi tôi quay lại bàn, anh ấy đã tự giới thiệu mình với ba cô gái ở bàn bên cạnh chúng tôi và biết tên họ. Anh ấy ở đó, nói những câu như 'Clare, em thích London thế nào?' Bạn có thể thấy Clare đang nghĩ 'Thật là một anh chàng tốt bụng.' Và tôi chắc chắn là anh ấy gọi cô ấy bằng tên. Thực ra, kể từ khi Ann gợi ý cuốn sách này, tôi đã đọc một vài cuốn sách khác của anh ấy. <br>\
ANN Vâng, gần đây tôi cũng đã mua một trong những cuốn sách khác của anh ấy.<br>\
AMY Vâng, trong vài tuần qua, thực ra tôi cũng đã thử một số gợi ý của Carnegie, bạn biết đấy, như cuốn mà anh ấy nói về sức mạnh của nụ cười.<br>\
ANN Vâng, nhưng điều đó đúng, phải không? Ý tôi là, hầu hết mọi người đều đi lại với vẻ mặt cau có. Vì vậy, khi ai đó thực sự mỉm cười với bạn, điều đó thực sự tạo ấn tượng.<br>\
AMY Đúng vậy! Bạn biết đấy, anh ấy gợi ý rằng hãy mỉm cười với mọi người mà bạn tiếp xúc trong một tuần và ghi lại những gì xảy ra. Vâng, tôi đã làm vậy và nó thực sự tạo ra sự khác biệt. Giống như, tôi đã đi đến cùng một nhà ga xe lửa trong nhiều năm và cho đến bây giờ, tôi chưa bao giờ thực sự có bất kỳ liên lạc nào với anh chàng ở phòng vé ngoài câu, 'Quay lại Richmond, làm ơn.' Vì vậy, tôi đã bắt đầu với anh ấy. Bạn biết đấy, một nụ cười và một chút giao tiếp bằng mắt và thật tuyệt vời! Anh ấy thực sự nói chuyện rất nhiều kể từ đó. Cách dễ chịu hơn nhiều để bắt đầu ngày mới. Và hãy nhớ đoạn mà Carnegie nói, ngay cả khi bạn không muốn cười, hãy ép mình phải cười, 'vì nụ cười thực sự mang lại cảm giác dễ chịu. Vâng, tôi cũng đã cố gắng làm điều đó và nó hiệu quả!<br>\
ANN Vâng, đó là một tư duy khác, phải không? Và tôi thích câu trích dẫn đó, câu tục ngữ Trung Quốc, 'Người đàn ông không có khuôn mặt tươi cười thì không nên mở cửa hàng!' Tôi biết, tôi biết một vài nhân viên bán hàng có thể học hỏi từ câu đó, đặc biệt là..."
		,voca:"",
	}
]