#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_watch.py - pipeline 1 lenh cho module Watch:
  1. Quet video trong watch/media (.mp4/.mkv/.mov/.webm)
  2. Video nao thieu .srt -> faster-whisper tao EN (VI de trong, tu dich tay)
  3. Sync vao listensrt/listensrtData.js (chi viet vung AUTO-SYNC, giu entry tay/Youtube)
  4. ID = ten file video (khong duoi) de de mapping.

Dung:
    python listensrt/sync_watch.py                      # quet + transcribe + sync
    python listensrt/sync_watch.py --sync-only           # chi sync .srt co san -> data.js
    python listensrt/sync_watch.py --force               # lam lai tu dau
    python listensrt/sync_watch.py --model small --lang en

Yeu cau: pip install faster-whisper deep-translator ; may co ffmpeg.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

# Windows console mac dinh cp1252 -> in emoji/tieng Viet loi. Ep utf-8.
try:
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_MEDIA = os.path.join(HERE, 'media')
DEFAULT_DATA = os.path.join(HERE, 'listensrtData.js')
VIDEO_EXTS = ('.mp4', '.mkv', '.mov', '.webm')
AUDIO_EXTS = ('.mp3', '.wav', '.m4a', '.ogg', '.oga', '.aac', '.flac')
MEDIA_EXTS = VIDEO_EXTS + AUDIO_EXTS
START_MARK = '/* AUTO-SYNC-START - do not edit: generated by listensrt/sync_watch.py */'
END_MARK = '/* AUTO-SYNC-END */'


def check_ffmpeg():
    if not shutil.which('ffmpeg'):
        sys.exit('❌ Khong tim thay ffmpeg. Cai ffmpeg va mo lai terminal.')


def media_duration(path):
    """Do dai video/audio (giay). Loi -> 0 (mac dinh dich VI)."""
    try:
        import json as _json
        r = subprocess.run(
            ['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
             '-of', 'json', path],
            capture_output=True, text=True, timeout=30)
        d = _json.loads(r.stdout or '{}')
        return float(d.get('format', {}).get('duration') or 0)
    except Exception:
        return 0


def extract_audio(video_path, audio_path):
    cmd = ['ffmpeg', '-y', '-i', video_path,
           '-ar', '16000', '-ac', '1', '-f', 'wav', audio_path]
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not os.path.exists(audio_path) or os.path.getsize(audio_path) == 0:
        raise RuntimeError('ffmpeg khong tach duoc audio: %s' % video_path)


def format_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    return '%02d:%02d:%02d,%03d' % (h, m, s, ms)


def load_srt(path):
    """Doc .srt -> [(start, end, text)]. File khong ton tai -> []."""
    if not os.path.exists(path):
        return []
    with open(path, encoding='utf-8-sig') as f:
        content = f.read().replace('\r\n', '\n').replace('\r', '\n')
    out = []
    for b in re.split(r'\n\s*\n', content.strip()):
        lines = [ln.strip() for ln in b.strip().split('\n') if ln.strip() != '']
        if len(lines) < 2:
            continue
        if re.match(r'^\d+$', lines[0]):
            lines = lines[1:]
        if len(lines) < 2 or '-->' not in lines[0]:
            continue
        ss, _, es = lines[0].partition('-->')
        text = re.sub(r'\s+', ' ', ' '.join(lines[1:])).strip()
        if text:
            out.append((ss.strip(), es.strip(), text))
    return out


def write_srt(path, segments):
    with open(path, 'w', encoding='utf-8') as f:
        for i, (s, e, t) in enumerate(segments):
            f.write('%d\n%s --> %s\n%s\n\n' % (i + 1, s, e, t))


def get_model(name):
    from faster_whisper import WhisperModel
    try:
        import torch
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    except Exception:
        device = 'cpu'
    compute = 'float16' if device == 'cuda' else 'int8'
    print('🧠 Model: %s (%s/%s)' % (name, device, compute))
    return WhisperModel(name, device=device, compute_type=compute)


def transcribe(video_path, model, lang, beam, word_times=True):
    tmp = tempfile.NamedTemporaryFile(suffix='.wav', delete=False)
    tmp.close()
    try:
        extract_audio(video_path, tmp.name)
        segments, _ = model.transcribe(tmp.name, beam_size=beam, language=lang,
                                       word_timestamps=word_times)
        out = []
        for seg in segments:
            t = seg.text.strip()
            if not t:
                continue
            s, e = seg.start, seg.end
            if word_times:
                # end cau = tu cuoi cung (+0.15s) thay vi het segment (toan silence thua)
                try:
                    ws = [w for w in (seg.words or []) if w.word.strip()]
                    if ws:
                        s = ws[0].start
                        e = ws[-1].end + 0.15
                except Exception:
                    pass
            out.append((format_time(s), format_time(e), t))
        return out
    finally:
        try:
            os.remove(tmp.name)
        except OSError:
            pass


def stem_title(stem):
    return re.sub(r'\s+', ' ', stem.replace('_', ' ').replace('-', ' ')).strip().title()


def js_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def natural_key(s):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]


def to_sec(ts):
    m = re.match(r'(\d+):(\d+):(\d+)[,.](\d+)', str(ts).strip())
    if not m:
        return 0.0
    h, mi, se, ms = map(int, m.groups())
    return h * 3600 + mi * 60 + se + ms / 1000.0


def fmt(x):
    h, r = divmod(int(x), 3600)
    m, s = divmod(r, 60)
    return '%02d:%02d:%02d' % (h, m, s)


def apply_gap(merged, gap):
    # 2 chieu (chi data sync, khong sua .srt):
    #  1) e thua cham t cau sau -> lui e (VD e=1542, next t=1542 -> e=1541.7)
    #  2) t chong len e cau truoc (dinh duoi tu) -> day t tre (VD t=957.0 -> 957.3)
    # Giu toi thieu 0.5s/cau. Giu nguyen cac field sau.
    if gap <= 0 or len(merged) < 2:
        return merged
    out = [list(m) for m in merged]
    for i in range(len(out) - 1):
        ns = to_sec(out[i + 1][0])
        e = to_sec(out[i][1])
        cap = ns - gap
        floor = to_sec(out[i][0]) + 0.5
        if e > cap and cap >= floor:
            out[i][1] = format_time(cap)
    for i in range(1, len(out)):
        pe = to_sec(out[i - 1][1])
        t = to_sec(out[i][0])
        e = to_sec(out[i][1])
        if t < pe:
            nt = min(pe + 0.3, e - 0.5)
            if nt > t:
                out[i][0] = format_time(nt)
    return [tuple(m) for m in out]


def check_segments(vf, merged):
    # Bao cau nghi van: chong lan / am gio / qua ngan / cach xa. Chi sua tay may dong nay.
    warns = []
    segs = [(to_sec(s), to_sec(e), t) for s, e, t in merged]
    for i, (s, e, t) in enumerate(segs):
        tag = t.split(' ||| ')[0][:42]
        if e <= s:
            warns.append('  ! #%d am gio (t>=e): %s..%s "%s"' % (i + 1, s, e, tag))
        elif e - s < 0.6:
            warns.append('  ! #%d qua ngan (%.1fs): "%s"' % (i + 1, e - s, tag))
        if i > 0:
            ps, pe, _ = segs[i - 1]
            if s < pe - 0.05:
                warns.append('  ! #%d chong cau truoc (t=%s < e=%s): "%s"'
                            % (i + 1, fmt(s), fmt(pe), tag))
            elif s - pe > 7:
                warns.append('  ! #%d cach cau truoc %.0fs (co the thieu cau): "%s"'
                            % (i + 1, s - pe, tag))
    return warns


def _js_unescape(s):
    return s.replace('\\\\', '\x00').replace("\\'", "'").replace('\\"', '"').replace('\\`', '`') \
        .replace('\\n', '\n').replace('\x00', '\\')


def _qmatch(m, base):
    # tra (inner, raw gom quote goc) tu 1 trong 3 nhom ', ", `
    for gi in (base, base + 1, base + 2):
        if m.group(gi) is not None:
            q = ["'", '"', '`'][gi - base]
            return m.group(gi), q + m.group(gi) + q
    return '', "''"


def parse_notes(content):
    # Doc note cu theo cau EN de giu lai khi sync.
    # Chiu moi kieu viet: note:'..' / note : ".." / note: `..`, truoc hay sau en.
    out = {}
    sq = r"'((?:[^'\\]|\\.)*)'"
    dq = r'"((?:[^"\\]|\\.)*)"'
    bq = r'`((?:[^`\\]|\\.)*)`'
    val = r'(?:%s|%s|%s)' % (sq, dq, bq)
    for m in re.finditer(r"en: %s[^}]*?note\s*:\s*%s" % (val, val), content):
        en, _ = _qmatch(m, 1)
        note, raw = _qmatch(m, 4)
        if _js_unescape(en) and note:
            out.setdefault(_js_unescape(en), raw)
    for m in re.finditer(r"note\s*:\s*%s[^}]*?en: %s" % (val, val), content):
        note, raw = _qmatch(m, 1)
        en, _ = _qmatch(m, 4)
        if _js_unescape(en) and note:
            out.setdefault(_js_unescape(en), raw)
    return out


def parse_existing(content):
    # Doc entry cu de GIU title/order/bIgnored sua tay khi sync lai
    out = {}
    for m in re.finditer(r"(\{\s*id: '((?:[^'\\]|\\.)*)'(.*?)\n\t\},)", content, flags=re.S):
        full, eid, body = m.group(1), m.group(2), m.group(3)
        t = re.search(r"\n\t\ttitle: ('(?:[^'\\]|\\.)*'),", body)
        o = re.search(r"\n\t\torder: (\d+),", body)
        b = re.search(r"\n\t\tbIgnored: (\d+),", body)
        out[eid] = {
            'title_raw': t.group(1) if t else None,
            'order': int(o.group(1)) if o else None,
            'bIgnored': int(b.group(1)) if b else 0,
            'raw': full,
            'has_subs': bool(re.search(r'\{ t:', body)),
        }
    return out


def render_title(template, stem, default_title):
    # {num02}: so trong ten file, pad 2 (SELAA_1 -> 01). {num}, {stem}, {title}
    if not template:
        return None
    m = re.search(r'(\d+)', stem)
    num = m.group(1) if m else ''
    return template.replace('{num02}', num.zfill(2)).replace('{num}', num or '?') \
        .replace('{stem}', stem).replace('{title}', default_title)


def entry_js(video_file, segments_vi, src_prefix='listensrt/media/', title_prefix='', order=None,
             title=None, bignored=0, title_raw=None, notes=None):
    stem = os.path.splitext(os.path.basename(video_file))[0]  # id = ten file (khong duong dan)
    lines = ['\t{',
             '\t\tid: %s,' % js_str(stem),
             '\t\tbIgnored: %d,' % (bignored or 0)]
    if order is not None:
        lines.append('\t\torder: %d,' % order)
    if title_raw is not None:
        lines.append('\t\ttitle: %s,' % title_raw)  # giu nguyen sua tay
    else:
        lines.append('\t\ttitle: %s,' % js_str(title if title is not None else title_prefix + stem_title(stem)))
    lines += ["\t\ttype: 'file',",
              '\t\tsrc: %s,' % js_str(src_prefix + video_file),
              '\t\tsubs: [']
    for j, (s, e, t) in enumerate(segments_vi):
        m = re.match(r'(\d+):(\d+):(\d+)[,.](\d+)', s)
        ts = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3)) + int(m.group(4)) / 1000.0
        m = re.match(r'(\d+):(\d+):(\d+)[,.](\d+)', e)
        te = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3)) + int(m.group(4)) / 1000.0
        en, _, vi = t.partition(' ||| ')
        line = '\t\t\t{ t: %.2f, e: %.2f, en: %s, vi: %s' % (ts, te, js_str(en), js_str(vi))
        if notes and j < len(notes) and notes[j]:
            line += ', note: %s' % notes[j]  # raw verbatim tu lan truoc
        lines.append(line + ' },')
    lines.append('\t\t]')
    lines.append('\t},')
    return '\n'.join(lines)


def sync_data(data_js, media_dir, video_files, gap=0.3, src_prefix='listensrt/media/',
              title_prefix='', order_start=None, title_template='', title_match=''):
    with open(data_js, encoding='utf-8') as f:
        content = f.read()
    if START_MARK not in content or END_MARK not in content:
        # tu chen markers vao cuoi mang (truoc ]; cuoi cung) thay vi bao loi
        idx = content.rfind('];')
        if idx < 0:
            sys.exit('❌ %s khong co mang LISTEN_DATA.' % data_js)
        content = (content[:idx] + START_MARK + '\n' + END_MARK + '\n'
                   + content[idx:])
        print('ℹ Tu them markers AUTO-SYNC vao %s' % data_js)
    keep = parse_existing(content)  # giu title/order/bIgnored sua tay
    old_notes = parse_notes(content)  # giu note theo cau EN
    blocks = []
    total_subs = 0
    all_warns = []
    ord_no = order_start
    for vf in sorted(video_files, key=natural_key):
        base = os.path.splitext(vf)[0]
        segs_en = load_srt(os.path.join(media_dir, base + '.srt'))
        segs_vi = load_srt(os.path.join(media_dir, base + '.vi.srt'))
        vi_by_en = {}
        for s, e, t in segs_vi:
            vi_by_en.setdefault((s, e), t)
        merged = []
        for s, e, t in segs_en:
            v = vi_by_en.get((s, e), '')
            if v.startswith('[LOI DICH]'):
                v = ''  # giu cho trong, app hien EN
            merged.append((s, e, t + ' ||| ' + v))
        merged = apply_gap(merged, gap)
        for w in check_segments(vf, merged):
            all_warns.append('  [%s] %s' % (vf, w))
        # note cu theo cau EN (ke ca khi sync lai)
        notes = [old_notes.get(t.split(' ||| ')[0], '') for (s, e, t) in merged]
        if not merged:
            # khong con .srt: giu nguyen entry cu (neu co) thay vi xoa bai
            stem0 = os.path.splitext(os.path.basename(vf))[0]
            old0 = keep.get(stem0, {})
            if old0.get('raw'):
                blocks.append(old0['raw'])
                total_subs += len(re.findall(r'\{ t:', old0['raw']))
                print('   📌 %s: khong co .srt -> giu entry cu trong data' % vf)
            else:
                print('   ⏭ %s: chua co .srt -> bo qua (chay transcribe truoc)' % vf)
            continue
        total_subs += len(merged)
        stem = os.path.splitext(os.path.basename(vf))[0]
        old = keep.get(stem, {})
        if title_template and (not title_match or title_match.lower() in vf.lower()):
            title, title_raw = render_title(title_template, stem, stem_title(stem)), None
        elif old.get('title_raw'):
            title, title_raw = None, old['title_raw']  # giu sua tay
        else:
            title, title_raw = None, None
        blocks.append(entry_js(vf, merged, src_prefix,
                               title_prefix if title is None and title_raw is None else '',
                               ord_no if ord_no is not None else old.get('order'),
                               title, old.get('bIgnored', 0), title_raw, notes))
        if ord_no is not None:
            ord_no += 1
    new_section = START_MARK + '\n' + '\n'.join(blocks) + '\n' + END_MARK if blocks \
        else START_MARK + '\n' + END_MARK
    pattern = re.compile(re.escape(START_MARK) + r'.*?' + re.escape(END_MARK), re.S)
    content = pattern.sub(lambda _: new_section, content, count=1)
    with open(data_js, 'w', encoding='utf-8') as f:
        f.write(content)
    print('✅ Sync %d video, %d dong sub -> %s' % (len(blocks), total_subs, data_js))
    if all_warns:
        print('🔍 Cau nghi van (sua tay trong .srt roi sync lai):')
        for w in all_warns[:40]:
            print(w)
        if len(all_warns) > 40:
            print('  ... con %d cau' % (len(all_warns) - 40))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--media-dir', default=DEFAULT_MEDIA)
    ap.add_argument('--data-js', default=DEFAULT_DATA)
    ap.add_argument('--model', default='base')
    ap.add_argument('--lang', default='en')
    ap.add_argument('--beam', type=int, default=5)
    ap.add_argument('--no-word-times', action='store_true',
                    help='tat word timestamps (nhanh hon chut, nhung gio e kem chuan)')
    ap.add_argument('--force', action='store_true', help='lam lai ca video da co .srt')
    ap.add_argument('--only', nargs='*', default=[],
                    help='chi xu ly cac file nay (stem, VD: --only 08VOA 09VOA)')
    ap.add_argument('--src-prefix', default='listensrt/media/',
                    help='tien to src trong data (VD: ebooks/lptd/data/cd1/ de dung file goc)')
    ap.add_argument('--title-prefix', default='',
                    help='tien to title (VD: "LPTD CD1 - ")')
    ap.add_argument('--title-template', default='',
                    help='mau title: {num02} so pad-2 trong ten file (VD: "SpeakEnglishLikeAnAmerican {num02}")')
    ap.add_argument('--title-match', default='',
                    help='chi ap template cho file chua chu nay (VD: SELAA). Trong thi ap het')
    ap.add_argument('--gap', type=float, default=0.3,
                    help='cat e thua + day t tre khoi vung chong lan, giay (default 0.3, 0 = tat)')
    ap.add_argument('--order-start', type=int, default=None,
                    help='danh order tu so nay, tang dan theo file')
    ap.add_argument('--sync-only', action='store_true', help='chi sync .srt co san, khong transcribe')
    a = ap.parse_args()

    if not os.path.isdir(a.media_dir):
        sys.exit('❌ Khong co thu muc: %s' % a.media_dir)
    videos = []
    for root, _, files in os.walk(a.media_dir):
        for fn in files:
            if fn.lower().endswith(MEDIA_EXTS):
                # giu duong dan tuong doi (subfolder) de src/srt map dung
                rel = os.path.relpath(os.path.join(root, fn), a.media_dir).replace(os.sep, '/')
                videos.append(rel)
    videos = sorted(videos)
    # mp4 nao da co mp3/wav cung ten thi ignore mp4 (nhe repo, khoi push video nang)
    aud_stems = {os.path.splitext(f)[0] for f in videos
                 if f.lower().endswith(AUDIO_EXTS)}
    kept = []
    for vf in videos:
        if vf.lower().endswith(VIDEO_EXTS) and os.path.splitext(vf)[0] in aud_stems:
            print('⏭ %s: da co audio cung ten -> bo qua video nang' % vf)
            continue
        kept.append(vf)
    videos = kept
    videos_all = kept[:]  # sync LUON full list (ke ca file --only bo qua)
    if a.only:
        want = {w.lower() for w in a.only}
        videos = [vf for vf in videos
                  if os.path.splitext(vf)[0].lower() in want or vf.lower() in want
                  or os.path.splitext(os.path.basename(vf))[0].lower() in want]
        if not videos:
            sys.exit('❌ --only khong khop file nao.')
    if not videos:
        print('ℹ %s chua co video (.mp4/.mkv/.mov/.webm).' % a.media_dir)
    print('🎬 %d video trong %s' % (len(videos), a.media_dir))

    model = None
    if not a.sync_only:
        check_ffmpeg()
        # entry da co subs trong data + khong .srt -> giu, khong transcribe lai
        old_keep_main = {}
        try:
            with open(a.data_js, encoding='utf-8') as _f:
                old_keep_main = parse_existing(_f.read())
        except Exception:
            pass
        for vf in videos:
            base = os.path.splitext(vf)[0]
            srt_en = os.path.join(a.media_dir, base + '.srt')
            srt_vi = os.path.join(a.media_dir, base + '.vi.srt')
            if os.path.exists(srt_en) and os.path.exists(srt_vi) and not a.force:
                print('✅ %s: da co EN+VI -> bo qua' % vf)
                continue
            stem_main = os.path.splitext(os.path.basename(vf))[0]
            if not os.path.exists(srt_en) and not a.force \
                    and old_keep_main.get(stem_main, {}).get('has_subs'):
                print('📌 %s: khong co .srt nhung data da co subs -> giu, khong transcribe' % vf)
                continue
            segs = None
            if os.path.exists(srt_en) and not a.force:
                # Co EN roi -> dung luon, khong transcribe lai
                segs = load_srt(srt_en)
                if segs:
                    print('📄 %s: dung EN .srt co san (%d dong)' % (vf, len(segs)))
                else:
                    print('📄 %s: EN .srt rong/hong -> transcribe lai' % vf)
                    segs = None
            if segs is None:
                if model is None:
                    model = get_model(a.model)
                print('📄 %s ...' % vf)
                try:
                    segs = transcribe(os.path.join(a.media_dir, vf), model, a.lang, a.beam,
                                      word_times=(not a.no_word_times))
                except Exception as e:
                    print('   ❌ transcribe loi: %s' % e)
                    continue
            if not segs:
                print('   ⚠ khong co segment -> bo qua')
                continue
            write_srt(srt_en, segs)
            print('   EN: %d dong' % len(segs))
            if not os.path.exists(srt_vi):
                write_srt(srt_vi, [(s, e, '') for s, e, _ in segs])
            print('   🎉 xong %s' % vf)

    sync_data(a.data_js, a.media_dir, videos_all, a.gap,
              a.src_prefix, a.title_prefix, a.order_start,
              a.title_template, a.title_match)


if __name__ == '__main__':
    main()
