#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_watch.py - pipeline 1 lenh cho module Watch:
  1. Quet video trong watch/media (.mp4/.mkv/.mov/.webm)
  2. Video nao thieu .srt -> faster-whisper tao EN, deep_translator dich VI
  3. Sync vao listensrt/listensrtData.js (chi viet vung AUTO-SYNC, giu entry tay/Youtube)
  4. ID = ten file video (khong duoi) de de mapping.

Dung:
    python listensrt/sync_watch.py                      # quet + transcribe + sync
    python listensrt/sync_watch.py --sync-only           # chi sync .srt co san -> data.js
    python listensrt/sync_watch.py --force               # lam lai tu dau
    python listensrt/sync_watch.py --model small --lang en

Yeu cau: pip install faster-whisper deep-translator ; may co ffmpeg.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

# Windows console mac dinh cp1252 -> in emoji/tieng Viet loi. Ep utf-8.
try:
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_MEDIA = os.path.join(HERE, 'media')
DEFAULT_DATA = os.path.join(HERE, 'listensrtData.js')
VIDEO_EXTS = ('.mp4', '.mkv', '.mov', '.webm')
AUDIO_EXTS = ('.mp3', '.wav', '.m4a', '.ogg', '.oga', '.aac', '.flac')
MEDIA_EXTS = VIDEO_EXTS + AUDIO_EXTS
START_MARK = '/* AUTO-SYNC-START - do not edit: generated by listensrt/sync_watch.py */'
END_MARK = '/* AUTO-SYNC-END */'


def check_ffmpeg():
    if not shutil.which('ffmpeg'):
        sys.exit('❌ Khong tim thay ffmpeg. Cai ffmpeg va mo lai terminal.')


def media_duration(path):
    """Do dai video/audio (giay). Loi -> 0 (mac dinh dich VI)."""
    try:
        import json as _json
        r = subprocess.run(
            ['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
             '-of', 'json', path],
            capture_output=True, text=True, timeout=30)
        d = _json.loads(r.stdout or '{}')
        return float(d.get('format', {}).get('duration') or 0)
    except Exception:
        return 0


def extract_audio(video_path, audio_path):
    cmd = ['ffmpeg', '-y', '-i', video_path,
           '-ar', '16000', '-ac', '1', '-f', 'wav', audio_path]
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not os.path.exists(audio_path) or os.path.getsize(audio_path) == 0:
        raise RuntimeError('ffmpeg khong tach duoc audio: %s' % video_path)


def format_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    return '%02d:%02d:%02d,%03d' % (h, m, s, ms)


def load_srt(path):
    """Doc .srt -> [(start, end, text)]. File khong ton tai -> []."""
    if not os.path.exists(path):
        return []
    with open(path, encoding='utf-8-sig') as f:
        content = f.read().replace('\r\n', '\n').replace('\r', '\n')
    out = []
    for b in re.split(r'\n\s*\n', content.strip()):
        lines = [ln.strip() for ln in b.strip().split('\n') if ln.strip() != '']
        if len(lines) < 2:
            continue
        if re.match(r'^\d+$', lines[0]):
            lines = lines[1:]
        if len(lines) < 2 or '-->' not in lines[0]:
            continue
        ss, _, es = lines[0].partition('-->')
        text = re.sub(r'\s+', ' ', ' '.join(lines[1:])).strip()
        if text:
            out.append((ss.strip(), es.strip(), text))
    return out


def write_srt(path, segments):
    with open(path, 'w', encoding='utf-8') as f:
        for i, (s, e, t) in enumerate(segments):
            f.write('%d\n%s --> %s\n%s\n\n' % (i + 1, s, e, t))


def get_model(name):
    from faster_whisper import WhisperModel
    try:
        import torch
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    except Exception:
        device = 'cpu'
    compute = 'float16' if device == 'cuda' else 'int8'
    print('🧠 Model: %s (%s/%s)' % (name, device, compute))
    return WhisperModel(name, device=device, compute_type=compute)


def transcribe(video_path, model, lang, beam, word_times=True):
    tmp = tempfile.NamedTemporaryFile(suffix='.wav', delete=False)
    tmp.close()
    try:
        extract_audio(video_path, tmp.name)
        segments, _ = model.transcribe(tmp.name, beam_size=beam, language=lang,
                                       word_timestamps=word_times)
        out = []
        for seg in segments:
            t = seg.text.strip()
            if not t:
                continue
            s, e = seg.start, seg.end
            if word_times:
                # end cau = tu cuoi cung (+0.15s) thay vi het segment (toan silence thua)
                try:
                    ws = [w for w in (seg.words or []) if w.word.strip()]
                    if ws:
                        s = ws[0].start
                        e = ws[-1].end + 0.15
                except Exception:
                    pass
            out.append((format_time(s), format_time(e), t))
        return out
    finally:
        try:
            os.remove(tmp.name)
        except OSError:
            pass


def translate_all(texts):
    """Dich list EN -> VI: Google truoc, rot xuong MyMemory (free, khac ha tang).
    Batch neu lib ho tro, retry + delay tranh rate-limit."""
    import time as _time
    from deep_translator import GoogleTranslator
    tr = GoogleTranslator(source='auto', target='vi')
    if not texts:
        return []
    # thu batch (deep_translator moi)
    if hasattr(tr, 'translate_batch'):
        for attempt in range(3):
            try:
                got = tr.translate_batch(texts)
                if got and len(got) == len(texts):
                    return [g if g else t for g, t in zip(got, texts)]
            except Exception as e:
                if attempt == 2:
                    print('   ⚠ batch fail, dich le: %s' % str(e)[:120])
                continue
    # MyMemory du phong (Google hay chan IP): khoi tao 1 lan
    mm = None
    try:
        from deep_translator import MyMemoryTranslator
        mm = MyMemoryTranslator(source='english us', target='vietnamese')
    except Exception as e:
        print('   ⚠ khong co MyMemory fallback: %s' % str(e)[:100])

    def via_mymemory(t):
        if not mm:
            return None
        for _ in range(2):
            try:
                g = mm.translate(t)
                if g and 'QUERY LENGTH LIMIT' not in g and 'INVALID' not in g.upper():
                    return g
            except Exception:
                continue
            _time.sleep(0.5)
        return None

    out = []
    for t in texts:
        done = None
        for _ in range(3):
            try:
                g = tr.translate(t)
                if g:
                    done = g
                    break
            except Exception:
                continue
        if done is None:
            done = via_mymemory(t)
        out.append(done if done else '[LOI DICH] ' + t)
        _time.sleep(0.4)  # Google gioi han ~5 req/s
    return out


def stem_title(stem):
    return re.sub(r'\s+', ' ', stem.replace('_', ' ').replace('-', ' ')).strip().title()


def js_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def entry_js(video_file, segments_vi, src_prefix='listensrt/media/', title_prefix='', order=None):
    stem = os.path.splitext(os.path.basename(video_file))[0]  # id = ten file (khong duong dan)
    lines = ['\t{',
             '\t\tid: %s,' % js_str(stem),
             '\t\tbIgnored: 0,']
    if order is not None:
        lines.append('\t\torder: %d,' % order)
    lines.append('\t\ttitle: %s,' % js_str(title_prefix + stem_title(stem)))
    lines += ["\t\ttype: 'file',",
              '\t\tsrc: %s,' % js_str(src_prefix + video_file),
              '\t\tsubs: [']
    for s, e, t in segments_vi:
        m = re.match(r'(\d+):(\d+):(\d+)[,.](\d+)', s)
        ts = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3)) + int(m.group(4)) / 1000.0
        m = re.match(r'(\d+):(\d+):(\d+)[,.](\d+)', e)
        te = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3)) + int(m.group(4)) / 1000.0
        en, _, vi = t.partition(' ||| ')
        lines.append('\t\t\t{ t: %.2f, e: %.2f, en: %s, vi: %s },' % (ts, te, js_str(en), js_str(vi)))
    lines.append('\t\t]')
    lines.append('\t},')
    return '\n'.join(lines)


def sync_data(data_js, video_files):
    with open(data_js, encoding='utf-8') as f:
        content = f.read()
    if START_MARK not in content or END_MARK not in content:
        # tu chen markers vao cuoi mang (truoc ]; cuoi cung) thay vi bao loi
        idx = content.rfind('];')
        if idx < 0:
            sys.exit('❌ %s khong co mang LISTEN_DATA.' % data_js)
        content = (content[:idx] + START_MARK + '\n' + END_MARK + '\n'
                   + content[idx:])
        print('ℹ Tu them markers AUTO-SYNC vao %s' % data_js)
    blocks = []
    total_subs = 0
    for vf in sorted(video_files):
        base = os.path.splitext(vf)[0]
        segs_en = load_srt(os.path.join(os.path.dirname(data_js), 'media', base + '.srt'))
        segs_vi = load_srt(os.path.join(os.path.dirname(data_js), 'media', base + '.vi.srt'))
        vi_by_en = {}
        for s, e, t in segs_vi:
            vi_by_en.setdefault((s, e), t)
        merged = []
        for s, e, t in segs_en:
            v = vi_by_en.get((s, e), '')
            if v.startswith('[LOI DICH]'):
                v = ''  # dich loi -> de trong, app hien EN (chay --retranslate sau)
            merged.append((s, e, t + ' ||| ' + v))
        if not merged:
            print('   ⏭ %s: chua co .srt -> bo qua (chay transcribe truoc)' % vf)
            continue
        total_subs += len(merged)
        blocks.append(entry_js(vf, merged))
    new_section = START_MARK + '\n' + '\n'.join(blocks) + '\n' + END_MARK if blocks \
        else START_MARK + '\n' + END_MARK
    pattern = re.compile(re.escape(START_MARK) + r'.*?' + re.escape(END_MARK), re.S)
    content = pattern.sub(lambda _: new_section, content, count=1)
    with open(data_js, 'w', encoding='utf-8') as f:
        f.write(content)
    print('✅ Sync %d video, %d dong sub -> %s' % (len(blocks), total_subs, data_js))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--media-dir', default=DEFAULT_MEDIA)
    ap.add_argument('--data-js', default=DEFAULT_DATA)
    ap.add_argument('--model', default='base')
    ap.add_argument('--lang', default='en')
    ap.add_argument('--beam', type=int, default=5)
    ap.add_argument('--no-word-times', action='store_true',
                    help='tat word timestamps (nhanh hon chut, nhung gio e kem chuan)')
    ap.add_argument('--force', action='store_true', help='lam lai ca video da co .srt')
    ap.add_argument('--only', nargs='*', default=[],
                    help='chi xu ly cac file nay (stem, VD: --only 08VOA 09VOA)')
    ap.add_argument('--src-prefix', default='listensrt/media/',
                    help='tien to src trong data (VD: ebooks/lptd/data/cd1/ de dung file goc)')
    ap.add_argument('--title-prefix', default='',
                    help='tien to title (VD: "LPTD CD1 - ")')
    ap.add_argument('--order-start', type=int, default=None,
                    help='danh order tu so nay, tang dan theo file')
    ap.add_argument('--no-vi', action='store_true',
                    help='bo dich VI (chi EN). Phu hop video dai / von tieng Anh tot')
    ap.add_argument('--vi-max-minutes', type=float, default=10,
                    help='video dai hon so phut nay thi tu bo dich VI (default 10, 0 = luon dich)')
    ap.add_argument('--retranslate', action='store_true',
                    help='chi dich lai VI tu EN .srt co san (khong transcribe)')
    ap.add_argument('--sync-only', action='store_true', help='chi sync .srt co san, khong transcribe')
    a = ap.parse_args()

    if not os.path.isdir(a.media_dir):
        sys.exit('❌ Khong co thu muc: %s' % a.media_dir)
    videos = []
    for root, _, files in os.walk(a.media_dir):
        for fn in files:
            if fn.lower().endswith(MEDIA_EXTS):
                # giu duong dan tuong doi (subfolder) de src/srt map dung
                rel = os.path.relpath(os.path.join(root, fn), a.media_dir).replace(os.sep, '/')
                videos.append(rel)
    videos = sorted(videos)
    # mp4 nao da co mp3/wav cung ten thi ignore mp4 (nhe repo, khoi push video nang)
    aud_stems = {os.path.splitext(f)[0] for f in videos
                 if f.lower().endswith(AUDIO_EXTS)}
    kept = []
    for vf in videos:
        if vf.lower().endswith(VIDEO_EXTS) and os.path.splitext(vf)[0] in aud_stems:
            print('⏭ %s: da co audio cung ten -> bo qua video nang' % vf)
            continue
        kept.append(vf)
    videos = kept
    videos_all = kept[:]  # sync LUON full list (ke ca file --only bo qua)
    if a.only:
        want = {w.lower() for w in a.only}
        videos = [vf for vf in videos
                  if os.path.splitext(vf)[0].lower() in want or vf.lower() in want
                  or os.path.splitext(os.path.basename(vf))[0].lower() in want]
        if not videos:
            sys.exit('❌ --only khong khop file nao.')
    if not videos:
        print('ℹ %s chua co video (.mp4/.mkv/.mov/.webm).' % a.media_dir)
    print('🎬 %d video trong %s' % (len(videos), a.media_dir))

    model = None
    if a.retranslate:
        for vf in videos:
            base = os.path.splitext(vf)[0]
            srt_en = os.path.join(a.media_dir, base + '.srt')
            if not os.path.exists(srt_en):
                print('⏭ %s: chua co EN .srt -> bo qua' % vf)
                continue
            print('🌐 Dich lai VI: %s ...' % vf)
            segs = load_srt(srt_en)
            vis = translate_all([t for _, _, t in segs])
            bad = sum(1 for v in vis if v.startswith('[LOI DICH]'))
            if bad >= len(vis) and vis:
                print('   ❌ dich that bai het. De mai/chuyen mang roi chay lai.')
            else:
                write_srt(os.path.join(a.media_dir, base + '.vi.srt'),
                          [(s, e, v) for (s, e, _), v in zip(segs, vis)])
                print('   🎉 xong (%d/%d loi)' % (bad, len(vis)) if bad else '   🎉 xong, khong loi')
    elif not a.sync_only:
        check_ffmpeg()
        for vf in videos:
            base = os.path.splitext(vf)[0]
            srt_en = os.path.join(a.media_dir, base + '.srt')
            srt_vi = os.path.join(a.media_dir, base + '.vi.srt')
            if os.path.exists(srt_en) and os.path.exists(srt_vi) and not a.force:
                print('✅ %s: da co EN+VI -> bo qua' % vf)
                continue
            segs = None
            if os.path.exists(srt_en) and not a.force:
                # Co EN roi -> dung luon, khong transcribe lai
                segs = load_srt(srt_en)
                if segs:
                    print('📄 %s: dung EN .srt co san (%d dong)' % (vf, len(segs)))
                else:
                    print('📄 %s: EN .srt rong/hong -> transcribe lai' % vf)
                    segs = None
            if segs is None:
                if model is None:
                    model = get_model(a.model)
                print('📄 %s ...' % vf)
                try:
                    segs = transcribe(os.path.join(a.media_dir, vf), model, a.lang, a.beam,
                                      word_times=(not a.no_word_times))
                except Exception as e:
                    print('   ❌ transcribe loi: %s' % e)
                    continue
            if not segs:
                print('   ⚠ khong co segment -> bo qua')
                continue
            write_srt(srt_en, segs)
            dur = media_duration(os.path.join(a.media_dir, vf))
            skip_vi = a.no_vi or (a.vi_max_minutes > 0 and dur > a.vi_max_minutes * 60)
            if skip_vi:
                print('   EN: %d dong (%.1f phut) -> bo dich VI' % (len(segs), dur / 60))
                write_srt(srt_vi, [(s, e, '') for s, e, _ in segs])
            else:
                print('   EN: %d dong -> dich VI...' % len(segs))
                vis = translate_all([t for _, _, t in segs])
                bad = sum(1 for v in vis if v.startswith('[LOI DICH]'))
                if bad >= len(vis):
                    # tat ca loi (mang chan) -> KHONG ghi file de lan sau dich lai
                    print('   ❌ dich that bai het (%d cau). De mai/chuyen mang roi chay --retranslate %s'
                          % (len(vis), os.path.splitext(vf)[0]))
                else:
                    write_srt(srt_vi, [(s, e, v) for (s, e, _), v in zip(segs, vis)])
                    if bad:
                        print('   ⚠ %d/%d cau loi dich (chay --retranslate sau)' % (bad, len(vis)))
            print('   🎉 xong %s' % vf)

    sync_data(a.data_js, videos_all)


if __name__ == '__main__':
    main()
