


const barron600_read_data = [
{
	unit:1,
	title:"[R] Environmental Impacts of Logging",
	en:"A<br>\
From shipping crates to paper bags, the logging industry supplies the raw materials for an array of products. However, this is not without untold harm to the environment. The damage includes habitat loss, pol- lution, and climate change, with the effects spanning the globe from the rain forests of Central Africa, Southeast Asia, and South America to the northern forests of Canada and Scandinavia. The effects of logging extend beyond just the felling of a swath of trees. Nutrients, water, and shelter for plants, animals, and microorganisms throughout the ecosys- tem are also lost; many life forms-both terrestrial and aquatic-are becoming endangered as forests vanish.<br>\
B<br>\
Trees protect the soil beneath them; thus, tree loss can affect soil integrity. For example, the rain forest floor, home to myriad plant life as well as insects, worms, reptiles and amphibians, and small mammals, relies on a dense canopy of branches and leaves to keep it healthy and intact. The canopy prevents surface runoff by intercepting heavy rainfall so that water can drip down slowly onto the porous earth. Tree roots also stabilize the soil and help prevent erosion. In return, a healthy soil encourages root development and microbial activity, which contribute to tree growth and well-being. A major factor in logging-related soll dam- age comes from road building, with trucks and other heavy equipment compressing the spongy soil, creating furrows where water collects, and disrupting the underground water flow. Eventually, the topsoil wears away, leaving behind an infertile layer of rocks and hard clay.<br>\
C<br>\
Logging can also damage aquatic habitats. Vegetation along rivers and stream banks helps maintain a steady water flow by blocking the entry of soll and other residue, and tree shade inhibits the growth of algae. Remov- ing trees obliterates these benefits. When eroding soil flows into water- ways, the organic matter within it consumes more oxygen, which can lead to oxygen depletion in the water, killing fish and other aquatic wildlife.<br>\
D<br>\
Trees provide a natural defense against air pollution. They remove car- bon dioxide from the atmosphere while they emit oxygen, and their leaves filter pollutants from the air. Cutting down trees keeps pollutants airborne, where they can mix with water vapor1 and form acid rain. Water quality in nearby streams and rivers also deteriorates as tree loss contributes to increased sedimentation.<br>\
E<br>\
In a healthy forest ecosystem, trees draw moisture from the soil and release it into the atmosphere while they provide shade to lessen evap- oration. Thus, deforestation impacts rainfall patterns, leading to flood- ing as well as drought and forest fires. Deforestation is responsible for about one-fifth of carbon dioxide emissions worldwide, making it a major contributor to climate change-in particular, global warming. In the Amazon basin alone, deforestation is responsible for millions of tons of carbon dioxide being released into the atmosphere annually. Some logging companies burn large tracts of forest just to facilitate access to one area-a practice? that discharges even more carbon dioxide.<br>\
F<br>\
Forests, especially the tropical rain forests, are a vital natural resource with extensive biodiversity and irreplaceable wildlife habitats. More responsible logging practices would help ensure that they are protected for future generations."
	,vi:"A<br>\
Từ thùng vận chuyển đến túi giấy, ngành khai thác gỗ cung cấp nguyên liệu thô cho một loạt các sản phẩm. Tuy nhiên, điều này không phải là không có tác hại không thể kể xiết đối với môi trường. Thiệt hại bao gồm mất môi trường sống, ô nhiễm và biến đổi khí hậu, với những tác động trải dài trên toàn cầu từ các khu rừng mưa ở Trung Phi, Đông Nam Á và Nam Mỹ đến các khu rừng phía bắc của Canada và Scandinavia. Tác động của việc khai thác gỗ không chỉ dừng lại ở việc chặt hạ một dải cây. Chất dinh dưỡng, nước và nơi trú ẩn cho thực vật, động vật và vi sinh vật trong toàn bộ hệ sinh thái cũng bị mất đi; nhiều dạng sống - cả trên cạn và dưới nước - đang bị đe dọa khi rừng biến mất.<br>\
B<br>\
Cây bảo vệ đất bên dưới chúng; do đó, việc mất cây có thể ảnh hưởng đến tính toàn vẹn của đất. Ví dụ, tầng rừng mưa, nơi sinh sống của vô số loài thực vật cũng như côn trùng, giun, bò sát và lưỡng cư, và động vật có vú nhỏ, phụ thuộc vào tán lá và cành cây rậm rạp để giữ cho nó khỏe mạnh và nguyên vẹn. Tán cây ngăn chặn dòng chảy bề mặt bằng cách chặn lượng mưa lớn để nước có thể nhỏ giọt từ từ xuống đất xốp. Rễ cây cũng ổn định đất và giúp ngăn ngừa xói mòn. Đổi lại, đất khỏe mạnh thúc đẩy sự phát triển của rễ và hoạt động của vi khuẩn, góp phần vào sự phát triển và sức khỏe của cây. Một yếu tố chính gây ra thiệt hại do khai thác gỗ liên quan đến việc làm đường, với xe tải và các thiết bị hạng nặng khác nén đất xốp, tạo ra các rãnh nơi nước đọng và làm gián đoạn dòng chảy của nước ngầm. Cuối cùng, lớp đất mặt bị xói mòn, để lại một lớp đá và đất sét cứng không màu mỡ.<br>\
C<br>\
Khai thác gỗ cũng có thể gây hại cho môi trường sống dưới nước. Thảm thực vật dọc theo bờ sông và bờ suối giúp duy trì dòng nước ổn định bằng cách ngăn chặn sự xâm nhập của đất và các chất thải khác, và bóng râm của cây ức chế sự phát triển của tảo. Việc chặt bỏ cây sẽ xóa bỏ những lợi ích này. Khi đất bị xói mòn chảy vào các dòng nước, chất hữu cơ bên trong đất sẽ tiêu thụ nhiều oxy hơn, có thể dẫn đến tình trạng cạn kiệt oxy trong nước, giết chết cá và các loài động vật hoang dã dưới nước khác.<br>\
D<br>\
Cây cối cung cấp khả năng phòng vệ tự nhiên chống lại ô nhiễm không khí. Chúng loại bỏ carbon dioxide khỏi khí quyển trong khi thải ra oxy và lá cây lọc các chất ô nhiễm từ không khí. Việc chặt cây khiến các chất ô nhiễm lơ lửng trong không khí, nơi chúng có thể trộn với hơi nước1 và tạo thành mưa axit. Chất lượng nước ở các suối và sông gần đó cũng xấu đi do mất cây góp phần làm tăng lắng đọng.<br>\
E<br>\
Trong một hệ sinh thái rừng khỏe mạnh, cây cối hút độ ẩm từ đất và giải phóng vào khí quyển trong khi chúng tạo bóng râm để giảm sự bốc hơi. Do đó, nạn phá rừng ảnh hưởng đến các kiểu mưa, dẫn đến lũ lụt cũng như hạn hán và cháy rừng. Nạn phá rừng là nguyên nhân gây ra khoảng một phần năm lượng khí thải carbon dioxide trên toàn thế giới, khiến nó trở thành tác nhân chính gây ra biến đổi khí hậu, đặc biệt là hiện tượng nóng lên toàn cầu. Chỉ riêng ở lưu vực sông Amazon, nạn phá rừng là nguyên nhân khiến hàng triệu tấn carbon dioxide được thải vào khí quyển hàng năm. Một số công ty khai thác gỗ đốt cháy những vùng rừng rộng lớn chỉ để tạo điều kiện tiếp cận một khu vực - một hoạt động thải ra nhiều carbon dioxide hơn.<br>\
F<br>\
Rừng, đặc biệt là rừng mưa nhiệt đới, là nguồn tài nguyên thiên nhiên quan trọng với đa dạng sinh học phong phú và môi trường sống của động vật hoang dã không thể thay thế. Các hoạt động khai thác gỗ có trách nhiệm hơn sẽ giúp đảm bảo rằng chúng được bảo vệ cho các thế hệ tương lai."
	,voca:"",
},
{
	unit:1,
	title:"[R] Bird Migration",
	en:"Migration is the regular movement of animals between their breeding grounds and the areas that they inhabit during the rest of the year. Many types of animals migrate, but bird migration in particular has fas- cinated observers for centuries. Migration is an excellent example of how nature has responded to the biological imperative for species to evolve and spread out into all possible ecological niches that can provide the conditions necessary for species to breed and raise young.<br>\
<br>\
The most common form of bird migration involves traveling1 to higher latitudes to breed during the warm season and then returning to lower latitudes during the nonbreeding period. This form of migration allows birds to breed in areas that provide optimal conditions for nesting and feeding their young. Because of the way in which the continents are sit- uated upon Earth, migration of this type takes place primarily into the higher latitudes of the Northern Hemisphere. No land birds are known to migrate into the higher latitudes of the Southern Hemisphere; only species of seabirds migrate to the Southern Hemisphere to breed.<br>\
<br>\
Although most bird migration takes place between the lower and higher latitudes of the Northern Hemisphere, many species are transe- quatorial, living in the Northern Hemisphere during the breeding season and in the Southern Hemisphere during the remainder of the year. A well-known example of transequatorial migration is the arctic tern. This tern, which breeds in the arctic regions and winters in antarctic waters, travels 24,000 miles a year during migration.<br>\
<br>\
Not all migration is long distance. Some species exhibit altitudinal migration. Their breeding areas are in higher elevations, near or at the peaks of mountains, and they spend the nonbreeding season in neighbor- ing2 valleys or other nearby low country. This variety of migration is typi- cal of many grouse species, including the ptarmigan, a type of arctic grouse. Many rock ptarmigan never leave the high arctic tundra, spend- ing their breeding season atop windswept arctic peaks and the winter sea- son in nearby valleys, enduring some of the coldest conditions on Earth. During migration, most birds fly for a limited period each day, proba- bly about six to eight hours, typically flying distances of several hundred miles. Some birds, however, undertake much longer flights when their routes include crossing large bodies of water or other geographic fea- tures such as deserts and mountains. For example, many species regu- larly cross the Gulf of Mexico, a trip that requires a continuous flight of more than 1,000 miles and takes from twenty-four to thirty-six hours or longer. An extreme example of nonstop bird migration is done by the miles from Alaska to New Zealand each year. At the start of its trip, about 55 percent of its body weight is made up of the fat necessary to fuel this amazing journey.<br>\
<br>\
How birds manage to unerringly travel between distant locations is one aspect that has fascinated observers for centuries. Modern-day researchers have attempted to understand this feat. Most studies have found that migratory birds all have some ability to navigate and an innate drive to travel in a particular direction. Nocturnal migrants, those species that travel at night, seem to take their navigational cues from the stars. When the stars are obscured by clouds, nocturnal migrants may become confused and return to land or stray off course. Diurnal migrants, those migrating during the day, take their cues from the loca- tion of the sun. In addition, diurnal migrants have also been shown to use geographic features such as mountain ranges or seacoasts as other cues for navigation. Because the stars and the sun move constantly over the course of twenty-four hours, this suggests that migrating birds also have some sense of time."
	,vi:"Di cư là sự di chuyển thường xuyên của động vật giữa nơi sinh sản của chúng và các khu vực mà chúng sinh sống trong suốt phần còn lại của năm. Nhiều loài động vật di cư, nhưng di cư của chim nói riêng đã thu hút sự chú ý của các nhà quan sát trong nhiều thế kỷ. Di cư là một ví dụ tuyệt vời về cách thiên nhiên phản ứng với nhu cầu sinh học bắt buộc các loài phải tiến hóa và lan rộng ra mọi hốc sinh thái có thể có, nơi có thể cung cấp các điều kiện cần thiết để các loài sinh sản và nuôi con non.<br>\
<br>\
Hình thức di cư phổ biến nhất của loài chim bao gồm di chuyển1 đến vĩ độ cao hơn để sinh sản trong mùa ấm và sau đó quay trở lại vĩ độ thấp hơn trong thời kỳ không sinh sản. Hình thức di cư này cho phép các loài chim sinh sản ở những khu vực cung cấp điều kiện tối ưu để làm tổ và nuôi con non. Do cách các lục địa nằm trên Trái đất, nên kiểu di cư này chủ yếu diễn ra ở các vĩ độ cao hơn của Bắc bán cầu. Không có loài chim trên cạn nào được biết là di cư đến các vĩ độ cao hơn của Nam bán cầu; chỉ có các loài chim biển di cư đến Nam bán cầu để sinh sản.<br>\
<br>\
Mặc dù hầu hết các loài chim di cư diễn ra giữa vĩ độ thấp hơn và cao hơn của Bắc bán cầu, nhiều loài di cư xuyên xích đạo, sống ở Bắc bán cầu trong mùa sinh sản và ở Nam bán cầu trong thời gian còn lại của năm. Một ví dụ nổi tiếng về di cư xuyên xích đạo là chim cốc Bắc Cực. Loài chim cốc này sinh sản ở các vùng Bắc Cực và trú đông ở vùng biển Nam Cực, di chuyển 24.000 dặm một năm trong quá trình di cư.<br>\
<br>\
Không phải tất cả các cuộc di cư đều là di cư đường dài. Một số loài thể hiện di cư theo độ cao. Khu vực sinh sản của chúng nằm ở độ cao lớn hơn, gần hoặc trên đỉnh núi, và chúng dành mùa không sinh sản ở các thung lũng lân cận hoặc vùng đất thấp gần đó. Kiểu di cư này là đặc trưng của nhiều loài chim gô, bao gồm cả gà gô trắng Bắc Cực. Nhiều loài gà gô đá không bao giờ rời khỏi vùng lãnh nguyên Bắc Cực cao, chúng dành mùa sinh sản trên đỉnh các đỉnh núi Bắc Cực lộng gió và mùa đông ở các thung lũng gần đó, chịu đựng một số điều kiện lạnh nhất trên Trái đất. Trong quá trình di cư, hầu hết các loài chim bay trong một khoảng thời gian giới hạn mỗi ngày, có thể khoảng sáu đến tám giờ, thường bay quãng đường dài vài trăm dặm. Tuy nhiên, một số loài chim thực hiện các chuyến bay dài hơn nhiều khi lộ trình của chúng bao gồm băng qua các vùng nước lớn hoặc các đặc điểm địa lý khác như sa mạc và núi. Ví dụ, nhiều loài thường xuyên băng qua Vịnh Mexico, một chuyến đi đòi hỏi phải bay liên tục hơn 1.000 dặm và mất từ ​​​​hai mươi bốn đến ba mươi sáu giờ hoặc lâu hơn. Một ví dụ cực đoan về cuộc di cư không ngừng của chim là hàng dặm từ Alaska đến New Zealand mỗi năm. Khi bắt đầu chuyến đi, khoảng 55 phần trăm trọng lượng cơ thể của chúng là chất béo cần thiết để cung cấp năng lượng cho chuyến hành trình tuyệt vời này.<br>\
<br>\
Cách các loài chim xoay xở để di chuyển chính xác giữa các địa điểm xa xôi là một khía cạnh đã khiến các nhà quan sát say mê trong nhiều thế kỷ. Các nhà nghiên cứu hiện đại đã cố gắng tìm hiểu kỳ tích này. Hầu hết các nghiên cứu đều phát hiện ra rằng tất cả các loài chim di cư đều có một số khả năng định hướng và bản năng di chuyển theo một hướng cụ thể. Những loài chim di cư về đêm, tức là những loài di chuyển vào ban đêm, dường như lấy tín hiệu định hướng từ các vì sao. Khi các vì sao bị mây che khuất, những loài chim di cư về đêm có thể bị nhầm lẫn và quay trở lại đất liền hoặc đi lạc hướng. Những loài chim di cư vào ban ngày, tức là những loài di cư vào ban ngày, lấy tín hiệu từ vị trí của mặt trời. Ngoài ra, những loài chim di cư vào ban ngày cũng được chứng minh là sử dụng các đặc điểm địa lý như dãy núi hoặc bờ biển làm tín hiệu định hướng khác. Vì các vì sao và mặt trời di chuyển liên tục trong suốt hai mươi bốn giờ, điều này cho thấy rằng những loài chim di cư cũng có một số ý thức về thời gian."
	,voca:"",
},
{
	unit:1,
	title:"[R] Plant Life in the Taklimakan Desert",
	en:"The Taklimakan Desert, second in size only to Africa's Sahara Desert, occupies some 337,600 square kilometers1 (130,300 square miles) of northwestern China-an area about the size of Finland. Sparse rainfall, daily temperature swings of up to 20°C (68°F), and violent sandstorms make it one of the most extreme environments on Earth.<br>\
<br>\
Eighty-five percent2 of the Taklimakan Desert consists of shifting sand dunes, some up to 250 meters3 tall, that are largely free of vegeta- tion. Yet, transitional areas between the open desert and oases on the desert fringe support diverse plant forms that not only have adapted to the harsh conditions but actually thrive there.<br>\
<br>\
Successful desert plants are resilient to scorching summers and frigid winters, drought, and high-salt conditions. The plants' principal defense against these environmental stressors consists of drawing in as much water as possible while minimizing moisture loss. Three Takli- makan plants-Populus euphratica, Tamarix ramosissima, and Alhagi sparsifolia represent some of the most diverse, prolific vegetation in the area; although they share many survival strategies, each has developed unique coping mechanisms of its own.<br>\
<br>\
The Euphrates poplar, Populus euphratica, the only tall tree in the Taklimakan ecosystem, has an extensive root system that allows it to absorb water far from the standing tree. P. euphratica controls evapora- tion by opening and closing the stomata, or tiny pores, on the leaf sur- face in response to the amount of moisture being lost through the leaves to the surrounding air. These stomata generally remain open during the day while the plant conducts photosynthesis.<br>\
<br>\
P. euphratica can endure high-salt concentrations in the soil. It takes in unlimited amounts of salt through the roots, up the stem, and into leaves, where it dilutes the normally toxic salt by increasing the number and volume of its cells.<br>\
<br>\
Tamarix ramosissima, a small tree with needlelike leaves commonly known as tamarisk or salt cedar, takes in enormous amounts of water via a far-reaching root system many times the size of the plant above ground. Like P. euphratica, tamarisk can naturally determine when to close stomata to inhibit evaporation and regulate photosynthesis.<br>\
<br>\
Tamarisk has a high tolerance for salty conditions and even produces its own salt, which it accumulates in special glands between the leaves and then releases onto leaf surfaces. Leaves dropping to the ground make the soil more saline, or salty, giving tamarisk a competitive advan- tage over less salt-tolerant plants.<br>\
Alhagi sparsifolia, a spiny shrub, thrives in the Taklimakan Desert even though it uses large amounts of water, especially during the sum- mer months. With only a few wispy roots in the upper soil, it is unaf- fected by occasional flooding. Most of its roots reach down deep, where they take up water from as far as sixteen meters below ground. Unlike P. euphratica and T. ramosissima, which open and close stomata accord- ing to conditions on the leaf surface, A. sparsifolia does so according to hydraulic conductance—that is, the ease with which it takes up ground- water.<br>\
<br>\
Although desert plants have adapted for their own survival, they also help protect their ecosystem by stabilizing sand dunes, preventing ero- sion, presenting a barrier to sandstorms, and conserving biodiversity."
	,vi:"Sa mạc Taklimakan, chỉ đứng thứ hai về diện tích sau sa mạc Sahara của Châu Phi, chiếm khoảng 337.600 kilômét vuông1 (130.300 dặm vuông) ở phía tây bắc Trung Quốc - một khu vực có diện tích bằng Phần Lan. Lượng mưa thưa thớt, nhiệt độ dao động hàng ngày lên tới 20°C (68°F) và những cơn bão cát dữ dội khiến nơi đây trở thành một trong những môi trường khắc nghiệt nhất trên Trái đất.<br>\
<br>\
Tám mươi lăm phần trăm2 sa mạc Taklimakan bao gồm các cồn cát di chuyển, một số cao tới 250 mét3, phần lớn không có thảm thực vật. Tuy nhiên, các khu vực chuyển tiếp giữa sa mạc rộng lớn và các ốc đảo ở rìa sa mạc hỗ trợ nhiều dạng thực vật không chỉ thích nghi với điều kiện khắc nghiệt mà còn thực sự phát triển mạnh ở đó.<br>\
<br>\
Những loài thực vật sa mạc phát triển tốt có khả năng chống chịu với mùa hè nóng nực và mùa đông giá lạnh, hạn hán và điều kiện độ mặn cao. Cơ chế phòng thủ chính của thực vật chống lại các tác nhân gây căng thẳng về môi trường này bao gồm việc hút càng nhiều nước càng tốt trong khi giảm thiểu mất độ ẩm. Ba loài thực vật Taklimakan - Populus euphratica, Tamarix ramosissima và Alhagi sparsifolia đại diện cho một số thảm thực vật đa dạng và phong phú nhất trong khu vực; mặc dù chúng có chung nhiều chiến lược sinh tồn, nhưng mỗi loài đều phát triển các cơ chế ứng phó độc đáo của riêng mình.<br>\
<br>\
Cây dương Euphrates, Populus euphratica, là loài cây cao duy nhất trong hệ sinh thái Taklimakan, có hệ thống rễ rộng cho phép nó hấp thụ nước ở xa cây đứng. P. euphratica kiểm soát sự bốc hơi bằng cách mở và đóng các lỗ khí khổng hoặc các lỗ chân lông nhỏ trên bề mặt lá để phản ứng với lượng độ ẩm bị mất qua lá vào không khí xung quanh. Các lỗ khí khổng này thường mở vào ban ngày trong khi cây tiến hành quang hợp.<br>\
<br>\
P. euphratica có thể chịu được nồng độ muối cao trong đất. Cây hấp thụ lượng muối không giới hạn qua rễ, lên thân và vào lá, tại đó, cây làm loãng lượng muối thường độc hại bằng cách tăng số lượng và thể tích tế bào.<br>\
<br>\
Tamarix ramosissima, một loại cây nhỏ có lá hình kim thường được gọi là tamarisk hoặc tuyết tùng muối, hấp thụ lượng nước khổng lồ thông qua hệ thống rễ lan rộng gấp nhiều lần kích thước của cây trên mặt đất. Giống như P. euphratica, tamarisk có thể tự nhiên xác định thời điểm đóng khí khổng để ức chế sự bốc hơi và điều chỉnh quá trình quang hợp.<br>\
<br>\
Tamarisk có khả năng chịu đựng cao với điều kiện mặn và thậm chí còn sản xuất ra muối của riêng mình, tích tụ trong các tuyến đặc biệt giữa các lá và sau đó giải phóng lên bề mặt lá. Lá rụng xuống đất làm cho đất mặn hơn, hoặc mặn hơn, mang lại cho cây tamarisk lợi thế cạnh tranh so với các loài thực vật ít chịu mặn hơn.<br>\
Alhagi sparsifolia, một loại cây bụi có gai, phát triển mạnh ở Sa mạc Taklimakan mặc dù nó sử dụng một lượng lớn nước, đặc biệt là trong những tháng mùa hè. Chỉ với một vài rễ mỏng manh ở lớp đất mặt, nó không bị ảnh hưởng bởi lũ lụt thỉnh thoảng. Hầu hết rễ của nó đâm sâu xuống đất, nơi chúng hấp thụ nước từ độ sâu tới mười sáu mét dưới lòng đất. Không giống như P. euphratica và T. ramosissima, mở và đóng khí khổng theo các điều kiện trên bề mặt lá, A. sparsifolia làm như vậy theo độ dẫn thủy lực—tức là, mức độ dễ dàng mà nó hấp thụ nước ngầm.<br>\
<br>\
Mặc dù các loài thực vật sa mạc đã thích nghi để tự sinh tồn, chúng cũng giúp bảo vệ hệ sinh thái của chúng bằng cách ổn định các cồn cát, ngăn chặn xói mòn, tạo thành rào cản đối với bão cát và bảo tồn đa dạng sinh học."
	,voca:"",
}

]